Refactor packaging workflow and remove unused files

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,47 +24,66 @@ jobs:
     - name: Install dependencies
       run: npm install
  
-    - name: Build
-      run: |
-        npm run build
+    # - name: Build
+    #   run: |
+    #     npm run build
       
 
-    - name: Check for defined tests
-      run: |
+    # - name: Check for defined tests
+    #   run: |
 
-        test_files=$(find . -name '*spec*.js')
-        if [ -z "$test_files" ]; then
-          echo "Error: No test files found."
-          exit 1
-        fi
+    #     test_files=$(find . -name '*spec*.js')
+    #     if [ -z "$test_files" ]; then
+    #       echo "Error: No test files found."
+    #       exit 1
+    #     fi
 
-    - name: Run tests
-      run: npm test
-        
+    # - name: Run tests
+    #   run: npm test
+       
+    - uses: testomatio/check-tests@stable
+      with:
+        framework: jest
+        tests: tests/**.spec.js
+        token: ${{ secrets.GITHUB_TOKEN }}
+
+
+
+
+
+
+
+
+
+
+
+
+
+
  
-  send_email_notification:
-        runs-on: ubuntu-latest
-        needs: test
-        if: ${{ needs.test.result == 'success' }}
-        steps:
-          - name: Send Email
-            if: always()
-            uses: hilarion5/send-mail@v1
-            with:
-              smtp-server: ${{ secrets.SMTP_NAME }}
-              smtp-port: 2525
-              smtp-secure: false
-              from-email: ${{ secrets.FROM_EMAIL }}
-              to-email: ${{ secrets.SMTP_TO_EMAIL }}
-              username: ${{ secrets.SMTP_USERNAME }}
-              password: ${{ secrets.SMTP_PASSWORD }}
-              subject: Workflows Status Notifications
-              body: |
+  # send_email_notification:
+  #       runs-on: ubuntu-latest
+  #       needs: test
+  #       if: ${{ needs.test.result == 'success' }}
+  #       steps:
+  #         - name: Send Email
+  #           if: always()
+  #           uses: hilarion5/send-mail@v1
+  #           with:
+  #             smtp-server: ${{ secrets.SMTP_NAME }}
+  #             smtp-port: 2525
+  #             smtp-secure: false
+  #             from-email: ${{ secrets.FROM_EMAIL }}
+  #             to-email: ${{ secrets.SMTP_TO_EMAIL }}
+  #             username: ${{ secrets.SMTP_USERNAME }}
+  #             password: ${{ secrets.SMTP_PASSWORD }}
+  #             subject: Workflows Status Notifications
+  #             body: |
                 
-                The build was ${{ needs.test.result }}.
-                ----------------------------------------------
-                Une nouvelle version de notre projet est disponible. Vous pouvez consulter la source du projet ici : https://github.com/${{ github.repository }}
-                ---------------------------------------------      
+  #               The build was ${{ needs.test.result }}.
+  #               ----------------------------------------------
+  #               Une nouvelle version de notre projet est disponible. Vous pouvez consulter la source du projet ici : https://github.com/${{ github.repository }}
+  #               ---------------------------------------------      
         
   # #Add the Cypress job for GUI tests
   # cypress:
